### PR TITLE
Provide a mechanism for generating entire tables

### LINKED ISSUE #6: add utility function for generating actual mock tables, not just a network of mocked records
I want to use MockTableGenerators to generate mock *tables*, but what it really supports out of the box is generating a network of mocked *records*; e.g. if I run the example code in the README the output is this data structure:

```jl
julia> # pass RNG for reproducible generation:
       collect(MockTableGenerators.generate(StableRNG(11), DAG))
41-element Vector{Any}:
  :person => (id = UUID("5a3d3d5e-ff13-417a-8b79-7c9e0c9cfb56"), first_name = "David", last_name = "Brown")
   :visit => (id = UUID("78899e60-eb7d-462d-9ed9-ef4e2046b221"), person_id = UUID("5a3d3d5e-ff13-417a-8b79-7c9e0c9cfb56"), index = 1, date = Date("1991-09-12"))
 :symptom => (visit_id = UUID("78899e60-eb7d-462d-9ed9-ef4e2046b221"), symptom = "Chills")
 :symptom => (visit_id = UUID("78899e60-eb7d-462d-9ed9-ef4e2046b221"), symptom = "Fever")
   :visit => (id = UUID("ac7d2f48-b1ae-4461-b3d7-85c527da1949"), person_id = UUID("5a3d3d5e-ff13-417a-8b79-7c9e0c9cfb56"), index = 2, date = Date("1995-11-04"))
 :symptom => (visit_id = UUID("ac7d2f48-b1ae-4461-b3d7-85c527da1949"), symptom = "Runny nose")
 :symptom => (visit_id = UUID("ac7d2f48-b1ae-4461-b3d7-85c527da1949"), symptom = "Runny nose")
  :person => (id = UUID("3c65b575-6628-4583-824e-a5340d3a02a8"), first_name = "Carol", last_name = "Johnson")
   :visit => (id = UUID("a8378ede-0d8b-4037-a6a6-aaa001ad216b"), person_id = UUID("3c65b575-6628-4583-824e-a5340d3a02a8"), index = 1, date = Date("1984-05-31"))
 :symptom => (visit_id = UUID("a8378ede-0d8b-4037-a6a6-aaa001ad216b"), symptom = "Fever")
 :symptom => (visit_id = UUID("a8378ede-0d8b-4037-a6a6-aaa001ad216b"), symptom = "Fever")
   :visit => (id = UUID("3375b4e2-da8d-4c63-987b-1beafa8088e4"), person_id = UUID("3c65b575-6628-4583-824e-a5340d3a02a8"), index = 2, date = Date("1991-12-26"))
 :symptom => (visit_id = UUID("3375b4e2-da8d-4c63-987b-1beafa8088e4"), symptom = "Chills")
 :symptom => (visit_id = UUID("3375b4e2-da8d-4c63-987b-1beafa8088e4"), symptom = "Chills")
   :visit => (id = UUID("515f665b-3f9e-458a-9a83-fdf8f3afdf66"), person_id = UUID("3c65b575-6628-4583-824e-a5340d3a02a8"), index = 3, date = Date("1995-01-10"))
 :symptom => (visit_id = UUID("515f665b-3f9e-458a-9a83-fdf8f3afdf66"), symptom = "Muscle Loss")
 :symptom => (visit_id = UUID("515f665b-3f9e-458a-9a83-fdf8f3afdf66"), symptom = "Fainting")
  :person => (id = UUID("7aef3538-782c-42b3-affb-ab188f985ce1"), first_name = "David", last_name = "Williams")
          ⋮
 :symptom => (visit_id = UUID("fe57c21d-fa08-4f2e-ab58-1c01ea7a2625"), symptom = "Muscle Loss")
 :symptom => (visit_id = UUID("fe57c21d-fa08-4f2e-ab58-1c01ea7a2625"), symptom = "Fainting")
  :person => (id = UUID("35131b5b-e0c7-4cb7-9ffc-cd5524c5617e"), first_name = "David", last_name = "Smith")
   :visit => (id = UUID("c8534847-0d27-441a-8c33-416586da8a9b"), person_id = UUID("35131b5b-e0c7-4cb7-9ffc-cd5524c5617e"), index = 1, date = Date("1983-11-22"))
 :symptom => (visit_id = UUID("c8534847-0d27-441a-8c33-416586da8a9b"), symptom = "Runny nose")
   :visit => (id = UUID("12cea550-51ac-4215-b58d-a2ec5fc14f9f"), person_id = UUID("35131b5b-e0c7-4cb7-9ffc-cd5524c5617e"), index = 2, date = Date("1996-03-27"))
 :symptom => (visit_id = UUID("12cea550-51ac-4215-b58d-a2ec5fc14f9f"), symptom = "Fatigue")
 :symptom => (visit_id = UUID("12cea550-51ac-4215-b58d-a2ec5fc14f9f"), symptom = "Fatigue")
   :visit => (id = UUID("0a01520e-1f7c-47f4-88d4-899bef6f0524"), person_id = UUID("35131b5b-e0c7-4cb7-9ffc-cd5524c5617e"), index = 3, date = Date("1998-04-29"))
 :symptom => (visit_id = UUID("0a01520e-1f7c-47f4-88d4-899bef6f0524"), symptom = "Muscle Loss")
 :symptom => (visit_id = UUID("0a01520e-1f7c-47f4-88d4-899bef6f0524"), symptom = "Fainting")
  :person => (id = UUID("5593e69f-b17b-41f9-a773-c2889a31cf14"), first_name = "Alice", last_name = "Johnson")
   :visit => (id = UUID("7cb41823-d331-41b9-82f1-90e940436b0c"), person_id = UUID("5593e69f-b17b-41f9-a773-c2889a31cf14"), index = 1, date = Date("1982-05-03"))
 :symptom => (visit_id = UUID("7cb41823-d331-41b9-82f1-90e940436b0c"), symptom = "Fatigue")
   :visit => (id = UUID("d27666c8-5183-4d7d-8c0e-23ff3dfb66df"), person_id = UUID("5593e69f-b17b-41f9-a773-c2889a31cf14"), index = 2, date = Date("1990-01-09"))
 :symptom => (visit_id = UUID("d27666c8-5183-4d7d-8c0e-23ff3dfb66df"), symptom = "Runny nose")
 :symptom => (visit_id = UUID("d27666c8-5183-4d7d-8c0e-23ff3dfb66df"), symptom = "Fatigue")
```

This is useful if I'm trying to upload this stream of dependent records in the intended order to an external storage system, but for simple flat-file-generation purposes I'd love it if I could do this:

```jl
julia> MockTableGenerators.generate_tables(StableRNG(11), DAG)
```
and just immediately get a `Vector` where each element is a `Table.jl`-compliant table, with the whole bundle generated in accordance with the given `DAG`

or can just place a `tablify` function in this package that converts the current `MockTableGenerators.generate` output to this form

### PR DESCRIPTION
**Pull request by ararslan**
This adds functions `collect_tables`, which turns the output of `generate` into a `NamedTuple` of tables, and `generate_tables` which is just a convenience atop `collect_tables(generate(...))`.

Example using the setup in the package's README:
```julia
julia> tables = MockTableGenerators.generate_tables(StableRNG(11), DAG);

julia> tables.person
5-element Vector{NamedTuple{(:id, :first_name, :last_name), Tuple{UUID, String, String}}}:
 (id = UUID("5a3d3d5e-ff13-417a-8b79-7c9e0c9cfb56"), first_name = "David", last_name = "Brown")
 (id = UUID("3c65b575-6628-4583-824e-a5340d3a02a8"), first_name = "Carol", last_name = "Johnson")
 (id = UUID("7aef3538-782c-42b3-affb-ab188f985ce1"), first_name = "David", last_name = "Williams")
 (id = UUID("35131b5b-e0c7-4cb7-9ffc-cd5524c5617e"), first_name = "David", last_name = "Smith")
 (id = UUID("5593e69f-b17b-41f9-a773-c2889a31cf14"), first_name = "Alice", last_name = "Johnson")

julia> tables.symptom
23-element Vector{NamedTuple{(:visit_id, :symptom), Tuple{UUID, String}}}:
 (visit_id = UUID("335cae41-dd9e-47c5-8628-da0e4daf1eca"), symptom = "Chills")
 (visit_id = UUID("335cae41-dd9e-47c5-8628-da0e4daf1eca"), symptom = "Fever")
 (visit_id = UUID("e5ed237f-6991-4eaf-8ab9-89d6862db6ea"), symptom = "Runny nose")
 (visit_id = UUID("e5ed237f-6991-4eaf-8ab9-89d6862db6ea"), symptom = "Runny nose")
 (visit_id = UUID("c1fd8091-1cad-4ff5-bc0a-c0ebd335c020"), symptom = "Fever")
 (visit_id = UUID("c1fd8091-1cad-4ff5-bc0a-c0ebd335c020"), symptom = "Fever")
 (visit_id = UUID("70754117-e13f-46ed-abfd-856153c66eea"), symptom = "Chills")
 (visit_id = UUID("70754117-e13f-46ed-abfd-856153c66eea"), symptom = "Chills")
 (visit_id = UUID("d2407228-04ac-43a3-bdc3-52d2140c6753"), symptom = "Muscle Loss")
 (visit_id = UUID("d2407228-04ac-43a3-bdc3-52d2140c6753"), symptom = "Fainting")
 (visit_id = UUID("84495b2f-11ec-4b38-9438-3a2912684539"), symptom = "Chills")
 (visit_id = UUID("5ddce3a4-3e12-4a48-ae05-b34ee5f0e074"), symptom = "Fatigue")
 (visit_id = UUID("5ddce3a4-3e12-4a48-ae05-b34ee5f0e074"), symptom = "Fever")
 (visit_id = UUID("3a2a8739-e004-4e5c-9ad5-5f529f10f507"), symptom = "Muscle Loss")
 (visit_id = UUID("3a2a8739-e004-4e5c-9ad5-5f529f10f507"), symptom = "Fainting")
 (visit_id = UUID("c5cdf617-56c6-452c-83ea-ca9c1975e1ac"), symptom = "Runny nose")
 (visit_id = UUID("a7ab506b-916d-4018-978a-b397500c48a5"), symptom = "Fatigue")
 (visit_id = UUID("a7ab506b-916d-4018-978a-b397500c48a5"), symptom = "Fatigue")
 (visit_id = UUID("016f4a4c-82b2-4c08-92cf-5274ef2c824a"), symptom = "Muscle Loss")
 (visit_id = UUID("016f4a4c-82b2-4c08-92cf-5274ef2c824a"), symptom = "Fainting")
 (visit_id = UUID("63cd1893-dea6-4eb2-9eaf-a6fbaf4adb05"), symptom = "Fatigue")
 (visit_id = UUID("5d5d7351-afbc-454d-9ba8-d6d1a2e14761"), symptom = "Runny nose")
 (visit_id = UUID("5d5d7351-afbc-454d-9ba8-d6d1a2e14761"), symptom = "Fatigue")

julia> tables.visit
13-element Vector{NamedTuple{(:id, :person_id, :index, :date), Tuple{UUID, UUID, Int64, Date}}}:
 (id = UUID("335cae41-dd9e-47c5-8628-da0e4daf1eca"), person_id = UUID("5a3d3d5e-ff13-417a-8b79-7c9e0c9cfb56"), index = 1, date = Date("1991-09-12"))
 (id = UUID("e5ed237f-6991-4eaf-8ab9-89d6862db6ea"), person_id = UUID("5a3d3d5e-ff13-417a-8b79-7c9e0c9cfb56"), index = 2, date = Date("1995-11-04"))
 (id = UUID("c1fd8091-1cad-4ff5-bc0a-c0ebd335c020"), person_id = UUID("3c65b575-6628-4583-824e-a5340d3a02a8"), index = 1, date = Date("1984-05-31"))
 (id = UUID("70754117-e13f-46ed-abfd-856153c66eea"), person_id = UUID("3c65b575-6628-4583-824e-a5340d3a02a8"), index = 2, date = Date("1991-12-26"))
 (id = UUID("d2407228-04ac-43a3-bdc3-52d2140c6753"), person_id = UUID("3c65b575-6628-4583-824e-a5340d3a02a8"), index = 3, date = Date("1995-01-10"))
 (id = UUID("84495b2f-11ec-4b38-9438-3a2912684539"), person_id = UUID("7aef3538-782c-42b3-affb-ab188f985ce1"), index = 1, date = Date("1981-01-02"))
 (id = UUID("5ddce3a4-3e12-4a48-ae05-b34ee5f0e074"), person_id = UUID("7aef3538-782c-42b3-affb-ab188f985ce1"), index = 2, date = Date("1981-12-14"))
 (id = UUID("3a2a8739-e004-4e5c-9ad5-5f529f10f507"), person_id = UUID("7aef3538-782c-42b3-affb-ab188f985ce1"), index = 3, date = Date("1992-07-11"))
 (id = UUID("c5cdf617-56c6-452c-83ea-ca9c1975e1ac"), person_id = UUID("35131b5b-e0c7-4cb7-9ffc-cd5524c5617e"), index = 1, date = Date("1983-11-22"))
 (id = UUID("a7ab506b-916d-4018-978a-b397500c48a5"), person_id = UUID("35131b5b-e0c7-4cb7-9ffc-cd5524c5617e"), index = 2, date = Date("1996-03-27"))
 (id = UUID("016f4a4c-82b2-4c08-92cf-5274ef2c824a"), person_id = UUID("35131b5b-e0c7-4cb7-9ffc-cd5524c5617e"), index = 3, date = Date("1998-04-29"))
 (id = UUID("63cd1893-dea6-4eb2-9eaf-a6fbaf4adb05"), person_id = UUID("5593e69f-b17b-41f9-a773-c2889a31cf14"), index = 1, date = Date("1982-05-03"))
 (id = UUID("5d5d7351-afbc-454d-9ba8-d6d1a2e14761"), person_id = UUID("5593e69f-b17b-41f9-a773-c2889a31cf14"), index = 2, date = Date("1990-01-09"))
```

Closes #6

I've had this change locally for months and had just forgotten to push it. 🙃

### CODE REVIEW

**Review by glennmoy — APPROVED** [review]
just needs a version bump :)

**Comment by ericphanson** [comment]
can we update the docs? E.g. the change in #8 should probably be replaced with this

**Comment by ararslan** [comment]
Version bumped, docs updated. Looks like #3 updated the README but not the docs, so the change made to the documentation is larger than it would otherwise be.

**Comment by ararslan** [comment]
Requesting re-review due to the docs change.

**Review by ericphanson — APPROVED** [review]

**Pull request merged**
